### ISSUE TITLE
Use either npm or yarn

### ISSUE THREAD

**Issue by aravindasiva** [rajeshmurugaiyan/myportfolio#2]
@rajeshmurugaiyan 
You are using npm and yarn 

if you are using yarn as your package manager remove [package-lock.json](https://github.com/rajeshmurugaiyan/myportfolio/blob/main/package-lock.json) file, because you have already got [yarn.lock](https://github.com/rajeshmurugaiyan/myportfolio/blob/main/yarn.lock)

**Comment by rajeshmurugaiyan** [comment]
ok, removed thanks
